#############################################################################
# Makefile for building: tortue
# Generated by qmake (3.1) (Qt 5.15.15)
# Project:  tortue.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile tortue.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++17 -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iexpressions -Iparser -IGUI -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = tortue1.0.0
DISTDIR = /home/marius/Nextcloud/marius/L3/théorie/tortueV4/.tmp/tortue1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = parser/main.cc \
		parser/driver.cc \
		parser/parser.cc \
		parser/scanner.cc \
		GUI/tortue.cc \
		GUI/jardinHandler.cc \
		GUI/jardinRendering.cc \
		GUI/jardin.cc \
		expressions/capteurs.cc \
		expressions/contexte.cc \
		expressions/constante.cc \
		expressions/variable.cc \
		expressions/expressionBinaire.cc \
		expressions/expressionUnaire.cc \
		expressions/expressionTernaire.cc \
		expressions/conditionBinaire.cc \
		expressions/testBinaire.cc moc_jardinHandler.cpp \
		moc_jardinRendering.cpp \
		moc_jardin.cpp
OBJECTS       = main.o \
		driver.o \
		parser.o \
		scanner.o \
		tortue.o \
		jardinHandler.o \
		jardinRendering.o \
		jardin.o \
		capteurs.o \
		contexte.o \
		constante.o \
		variable.o \
		expressionBinaire.o \
		expressionUnaire.o \
		expressionTernaire.o \
		conditionBinaire.o \
		testBinaire.o \
		moc_jardinHandler.o \
		moc_jardinRendering.o \
		moc_jardin.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		tortue.pro parser/scanner.hh \
		parser/driver.hh \
		parser/parser.hh \
		GUI/tortue.hh \
		GUI/jardinHandler.hh \
		GUI/jardinRendering.hh \
		GUI/jardin.hh \
		expressions/instructions.hh \
		expressions/capteurs.hh \
		expressions/types.hh \
		expressions/contexte.hh \
		expressions/expression.hh \
		expressions/expressionBinaire.hh \
		expressions/constante.hh \
		expressions/variable.hh \
		expressions/condition.hh \
		expressions/conditionBinaire.hh \
		expressions/testBinaire.hh \
		expressions/expressionUnaire.hh \
		expressions/expressionTernaire.hh parser/main.cc \
		parser/driver.cc \
		parser/parser.cc \
		parser/scanner.cc \
		GUI/tortue.cc \
		GUI/jardinHandler.cc \
		GUI/jardinRendering.cc \
		GUI/jardin.cc \
		expressions/capteurs.cc \
		expressions/contexte.cc \
		expressions/constante.cc \
		expressions/variable.cc \
		expressions/expressionBinaire.cc \
		expressions/expressionUnaire.cc \
		expressions/expressionTernaire.cc \
		expressions/conditionBinaire.cc \
		expressions/testBinaire.cc
QMAKE_TARGET  = tortue
DESTDIR       = 
TARGET        = tortue


first: all
####### Build rules

tortue:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: tortue.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		tortue.pro
	$(QMAKE) -o Makefile tortue.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
tortue.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile tortue.pro

qmake_all: FORCE


all: Makefile tortue

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents parser/scanner.hh parser/driver.hh parser/parser.hh GUI/tortue.hh GUI/jardinHandler.hh GUI/jardinRendering.hh GUI/jardin.hh expressions/instructions.hh expressions/capteurs.hh expressions/types.hh expressions/contexte.hh expressions/expression.hh expressions/expressionBinaire.hh expressions/constante.hh expressions/variable.hh expressions/condition.hh expressions/conditionBinaire.hh expressions/testBinaire.hh expressions/expressionUnaire.hh expressions/expressionTernaire.hh $(DISTDIR)/
	$(COPY_FILE) --parents parser/main.cc parser/driver.cc parser/parser.cc parser/scanner.cc GUI/tortue.cc GUI/jardinHandler.cc GUI/jardinRendering.cc GUI/jardin.cc expressions/capteurs.cc expressions/contexte.cc expressions/constante.cc expressions/variable.cc expressions/expressionBinaire.cc expressions/expressionUnaire.cc expressions/expressionTernaire.cc expressions/conditionBinaire.cc expressions/testBinaire.cc $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++17 -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_jardinHandler.cpp moc_jardinRendering.cpp moc_jardin.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_jardinHandler.cpp moc_jardinRendering.cpp moc_jardin.cpp
moc_jardinHandler.cpp: GUI/jardinHandler.hh \
		parser/parser.hh \
		expressions/contexte.hh \
		expressions/expression.hh \
		expressions/expressionBinaire.hh \
		expressions/expressionUnaire.hh \
		expressions/constante.hh \
		expressions/variable.hh \
		expressions/instructions.hh \
		expressions/condition.hh \
		expressions/capteurs.hh \
		expressions/types.hh \
		expressions/conditionBinaire.hh \
		expressions/testBinaire.hh \
		parser/location.hh \
		parser/scanner.hh \
		parser/driver.hh \
		GUI/jardinRendering.hh \
		GUI/tortue.hh \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/marius/Nextcloud/marius/L3/théorie/tortueV4/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/marius/Nextcloud/marius/L3/théorie/tortueV4 -I/home/marius/Nextcloud/marius/L3/théorie/tortueV4/expressions -I/home/marius/Nextcloud/marius/L3/théorie/tortueV4/parser -I/home/marius/Nextcloud/marius/L3/théorie/tortueV4/GUI -I/home/marius/Nextcloud/marius/L3/théorie/tortueV4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/x86_64-linux-gnu/c++/14 -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-linux-gnu/14/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include GUI/jardinHandler.hh -o moc_jardinHandler.cpp

moc_jardinRendering.cpp: GUI/jardinRendering.hh \
		GUI/tortue.hh \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/marius/Nextcloud/marius/L3/théorie/tortueV4/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/marius/Nextcloud/marius/L3/théorie/tortueV4 -I/home/marius/Nextcloud/marius/L3/théorie/tortueV4/expressions -I/home/marius/Nextcloud/marius/L3/théorie/tortueV4/parser -I/home/marius/Nextcloud/marius/L3/théorie/tortueV4/GUI -I/home/marius/Nextcloud/marius/L3/théorie/tortueV4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/x86_64-linux-gnu/c++/14 -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-linux-gnu/14/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include GUI/jardinRendering.hh -o moc_jardinRendering.cpp

moc_jardin.cpp: GUI/jardin.hh \
		GUI/jardinRendering.hh \
		GUI/tortue.hh \
		GUI/jardinHandler.hh \
		parser/parser.hh \
		expressions/contexte.hh \
		expressions/expression.hh \
		expressions/expressionBinaire.hh \
		expressions/expressionUnaire.hh \
		expressions/constante.hh \
		expressions/variable.hh \
		expressions/instructions.hh \
		expressions/condition.hh \
		expressions/capteurs.hh \
		expressions/types.hh \
		expressions/conditionBinaire.hh \
		expressions/testBinaire.hh \
		parser/location.hh \
		parser/scanner.hh \
		parser/driver.hh \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/marius/Nextcloud/marius/L3/théorie/tortueV4/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/marius/Nextcloud/marius/L3/théorie/tortueV4 -I/home/marius/Nextcloud/marius/L3/théorie/tortueV4/expressions -I/home/marius/Nextcloud/marius/L3/théorie/tortueV4/parser -I/home/marius/Nextcloud/marius/L3/théorie/tortueV4/GUI -I/home/marius/Nextcloud/marius/L3/théorie/tortueV4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/x86_64-linux-gnu/c++/14 -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-linux-gnu/14/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include GUI/jardin.hh -o moc_jardin.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: parser/main.cc parser/driver.hh \
		expressions/contexte.hh \
		expressions/instructions.hh \
		expressions/expression.hh \
		expressions/condition.hh \
		GUI/jardinRendering.hh \
		GUI/tortue.hh \
		expressions/types.hh \
		GUI/jardinHandler.hh \
		parser/parser.hh \
		expressions/expressionBinaire.hh \
		expressions/expressionUnaire.hh \
		expressions/constante.hh \
		expressions/variable.hh \
		expressions/capteurs.hh \
		expressions/conditionBinaire.hh \
		expressions/testBinaire.hh \
		parser/location.hh \
		parser/scanner.hh \
		GUI/jardin.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o parser/main.cc

driver.o: parser/driver.cc parser/driver.hh \
		expressions/contexte.hh \
		expressions/instructions.hh \
		expressions/expression.hh \
		expressions/condition.hh \
		GUI/jardinRendering.hh \
		GUI/tortue.hh \
		expressions/types.hh \
		GUI/jardinHandler.hh \
		parser/parser.hh \
		expressions/expressionBinaire.hh \
		expressions/expressionUnaire.hh \
		expressions/constante.hh \
		expressions/variable.hh \
		expressions/capteurs.hh \
		expressions/conditionBinaire.hh \
		expressions/testBinaire.hh \
		parser/location.hh \
		parser/scanner.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o driver.o parser/driver.cc

parser.o: parser/parser.cc parser/parser.hh \
		expressions/contexte.hh \
		expressions/expression.hh \
		expressions/expressionBinaire.hh \
		expressions/expressionUnaire.hh \
		expressions/constante.hh \
		expressions/variable.hh \
		expressions/instructions.hh \
		expressions/condition.hh \
		expressions/capteurs.hh \
		expressions/types.hh \
		expressions/conditionBinaire.hh \
		expressions/testBinaire.hh \
		parser/location.hh \
		parser/scanner.hh \
		parser/driver.hh \
		GUI/jardinRendering.hh \
		GUI/tortue.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser.o parser/parser.cc

scanner.o: parser/scanner.cc parser/scanner.hh \
		parser/parser.hh \
		expressions/contexte.hh \
		expressions/expression.hh \
		expressions/expressionBinaire.hh \
		expressions/expressionUnaire.hh \
		expressions/constante.hh \
		expressions/variable.hh \
		expressions/instructions.hh \
		expressions/condition.hh \
		expressions/capteurs.hh \
		expressions/types.hh \
		expressions/conditionBinaire.hh \
		expressions/testBinaire.hh \
		parser/location.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scanner.o parser/scanner.cc

tortue.o: GUI/tortue.cc GUI/tortue.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tortue.o GUI/tortue.cc

jardinHandler.o: GUI/jardinHandler.cc GUI/jardinHandler.hh \
		parser/parser.hh \
		expressions/contexte.hh \
		expressions/expression.hh \
		expressions/expressionBinaire.hh \
		expressions/expressionUnaire.hh \
		expressions/constante.hh \
		expressions/variable.hh \
		expressions/instructions.hh \
		expressions/condition.hh \
		expressions/capteurs.hh \
		expressions/types.hh \
		expressions/conditionBinaire.hh \
		expressions/testBinaire.hh \
		parser/location.hh \
		parser/scanner.hh \
		parser/driver.hh \
		GUI/jardinRendering.hh \
		GUI/tortue.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jardinHandler.o GUI/jardinHandler.cc

jardinRendering.o: GUI/jardinRendering.cc GUI/jardinRendering.hh \
		GUI/tortue.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jardinRendering.o GUI/jardinRendering.cc

jardin.o: GUI/jardin.cc GUI/jardin.hh \
		GUI/jardinRendering.hh \
		GUI/tortue.hh \
		GUI/jardinHandler.hh \
		parser/parser.hh \
		expressions/contexte.hh \
		expressions/expression.hh \
		expressions/expressionBinaire.hh \
		expressions/expressionUnaire.hh \
		expressions/constante.hh \
		expressions/variable.hh \
		expressions/instructions.hh \
		expressions/condition.hh \
		expressions/capteurs.hh \
		expressions/types.hh \
		expressions/conditionBinaire.hh \
		expressions/testBinaire.hh \
		parser/location.hh \
		parser/scanner.hh \
		parser/driver.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jardin.o GUI/jardin.cc

capteurs.o: expressions/capteurs.cc expressions/capteurs.hh \
		expressions/condition.hh \
		expressions/contexte.hh \
		expressions/types.hh \
		parser/driver.hh \
		expressions/instructions.hh \
		expressions/expression.hh \
		GUI/jardinRendering.hh \
		GUI/tortue.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o capteurs.o expressions/capteurs.cc

contexte.o: expressions/contexte.cc expressions/contexte.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contexte.o expressions/contexte.cc

constante.o: expressions/constante.cc expressions/constante.hh \
		expressions/expression.hh \
		expressions/contexte.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o constante.o expressions/constante.cc

variable.o: expressions/variable.cc expressions/variable.hh \
		expressions/expression.hh \
		expressions/contexte.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o variable.o expressions/variable.cc

expressionBinaire.o: expressions/expressionBinaire.cc expressions/expressionBinaire.hh \
		expressions/expression.hh \
		expressions/contexte.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o expressionBinaire.o expressions/expressionBinaire.cc

expressionUnaire.o: expressions/expressionUnaire.cc expressions/expressionUnaire.hh \
		expressions/expression.hh \
		expressions/contexte.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o expressionUnaire.o expressions/expressionUnaire.cc

expressionTernaire.o: expressions/expressionTernaire.cc expressions/expressionTernaire.hh \
		expressions/expression.hh \
		expressions/contexte.hh \
		expressions/condition.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o expressionTernaire.o expressions/expressionTernaire.cc

conditionBinaire.o: expressions/conditionBinaire.cc expressions/conditionBinaire.hh \
		expressions/condition.hh \
		expressions/contexte.hh \
		expressions/types.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o conditionBinaire.o expressions/conditionBinaire.cc

testBinaire.o: expressions/testBinaire.cc expressions/testBinaire.hh \
		expressions/expression.hh \
		expressions/contexte.hh \
		expressions/condition.hh \
		expressions/types.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testBinaire.o expressions/testBinaire.cc

moc_jardinHandler.o: moc_jardinHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_jardinHandler.o moc_jardinHandler.cpp

moc_jardinRendering.o: moc_jardinRendering.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_jardinRendering.o moc_jardinRendering.cpp

moc_jardin.o: moc_jardin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_jardin.o moc_jardin.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

